[package]
name = "ose_classes"
version = "0.1.0"
edition = "2021"

[dependencies]
# dicey = { path = "../dicey" }

comfy-table = "7.1.1"
serde = { version = "1.0.214", features = ["derive"]}
serde_json = "1.0.132"
strum = { version = "0.26.3", features = ["derive"] }
num-format = "0.4.4"
